### ISSUE TITLE
Majora's Mask (VC) 30 FPS toggle button

### ISSUE THREAD

**Issue by grimux** [Admentus64/Dolphin-Modding#1]
Would it be possible to change the button associated with the 30 FPS toggle?

As it stands, D-Pad Up conflicts while playing Redux: Majora's as the hack uses the D-Pad to change masks.

Could it be changed to Minus (-)?  This would be the same as in Ocarina of Time (VC).

Thank you so much!  I love your work!

**Comment by Admentus64** [comment]
Riiiight. Guess I forgot to update some of the codes for Majora's Mask when I last updated them for Ocarina of Time. Should by synced with more own collection once more. Classic Controller is required now.
